### ISSUE TITLE
Error dump username

### ISSUE THREAD

**Issue by Rhakim** [warifp/FacebookToolkit#1]
Saya mencoba fitur dump username. namun hasil yang didapat seperti screenshot dibawah ini.

![Screenshot_2019-06-13_00-41-42](https://user-images.githubusercontent.com/12286739/59391477-b68e1b80-8d74-11e9-90ce-fda59457a862.png)

**Comment by warifp** [comment]
![dump-usernamedone](https://user-images.githubusercontent.com/28912230/59417408-6bfeb480-8df1-11e9-9826-4291a2f33887.PNG)

Sudah bisa kembali mas, silahkan **clone** lagi, terimakasih
