### ISSUE TITLE
After installing the program and composer, the program doesn't run

### ISSUE THREAD

**Issue by Touexe** [warifp/FacebookToolkit#11]
php run.php

Oops, additional programs are needed to run this tool.

Start a check for needs..
====================================================================================================> 100%

Congratulations, the requirements for the program have been fulfilled.

 _______  _______    _       _      ||
|       ||       | _| |_   _| |_    || Author  : Wahyu Arif Purnomo
|    ___||_     _||_   _| |_   _|   || Version : 1.4
|   |___   |   |    |_|     |_|     || Build   : 8 June 2019
|    ___|  |   |                    || Update  : 15 June 2019
|   |      |   | Facebook Toolkit++ || Name    : Facebook Toolkit++
|___|      |___|        @2019       ||

[!] a tool to get Facebook data, and some Facebook bots, and extra tools found on Facebook Toolkit++

it stops right here !

**Comment by Touexe** [comment]
![Screenshot at 2019-08-24 03-19-10](https://user-images.githubusercontent.com/51247539/63631986-05321e80-c61e-11e9-94ab-0f069a8dcc5b.png)

**Comment by warifp** [comment]
**Please check, friend, this tool is already active again :D**

**Comment by NTgitdude23** [comment]
I am also getting the exact same output after attempting to run program with php run.php.  My computer has the exact output as  Touexe 's screenshot.

**Comment by textnowid** [comment]
How to run this tool after getting token Access.          I mean --help --update Etc

**Comment by Lucky97** [comment]
@textnowid how you got token ? please tell me any safe method  my 10+ accounts got checkpoint

**Comment by textnowid** [comment]
yes that right...........  my account also got check point several time................ can you tell me how to use this tool.......thanks in advance...... 😁😁

**Comment by Lucky97** [comment]
@textnowid will tell you how to use  this tool but please can you tell me any safe method for genrate token ?

**Comment by Lucky97** [comment]
@textnowid whats your whatsapp

**Comment by textnowid** [comment]
Don't have any you can have my fb id

**Comment by Lucky97** [comment]
@textnowid ok send your fb

**Comment by textnowid** [comment]
Md Kabir Hossain Shakil

**Comment by Lucky97** [comment]
https://www.facebook.com/profile.php?id=100013525770744 this ?

**Comment by textnowid** [comment]
Yep

**Comment by textnowid** [comment]
https://www.facebook.com/100013525770

**Comment by Lucky97** [comment]
check your msg request

**Comment by textnowid** [comment]
Hey bro follow my next link

**Comment by textnowid** [comment]
https://www.facebook.com/100013525770744

**Comment by textnowid** [comment]
Hey bro got nothing
