### ISSUE TITLE
eror dump email

### ISSUE THREAD

**Issue by rizkyundetect** [warifp/FacebookToolkit#2]
You have selected tools dump email your friends

load the tool you requested
======================================================================> 100%

Found 838 email addresses

Starting retrieve email your friends..
======================================================================> 100%

Done, your result saved in folder "result/result_email.txt"

setelah cek di result,gaada email 1 pun yg ke dupm

**Comment by warifp** [comment]
![done_dump](https://user-images.githubusercontent.com/28912230/59416787-4c1ac100-8df0-11e9-8c9e-c7283c272253.PNG)

Bisa mas, bisa dijelaskan mas, mas pakai linux atau windows?

**Comment by sheptiannahr** [comment]
permasalahan ane jg sma kayak diatas, saya menggunakan Android

**Comment by warifp** [comment]
Sudah saya perbarui mas, silahkan clone kembali, terimakasih.
