### ISSUE TITLE
cURL not found!

### ISSUE THREAD

**Issue by DarkSyntax7** [warifp/FacebookToolkit#28]
**It always shows cURL not found! Please install cURL.**
But cURL is already installed in my linux with updated version.
What can i do now??? Please tell.... @warifp 
![2020-05-30_14-24](https://user-images.githubusercontent.com/66020029/83324217-665be200-a281-11ea-93ee-5dde240f8003.png)

**Comment by Jashan-Khaira** [comment]
same issue i am facing can u plzz help warifp

**Comment by 0um4r** [comment]
I had the same problem. Let's see how fix it !

1. php --version
2. sudo apt-get install phpYOURVERSION-curl
3. sudo service apache2 restart


<img width="960" alt="fix" src="https://user-images.githubusercontent.com/21963422/88479361-e4212e80-cf4e-11ea-93ee-9dc1ec680646.png">

Then it should work.

**Comment by cyberred2020** [comment]
Tnx for this solution!
It is starting and after this is will go back to the terminal input and stops working:

![Screenshot from 2020-07-31 01-18-20](https://user-images.githubusercontent.com/69018315/88983594-713eed00-d299-11ea-8933-c25341e62168.png)
