### ISSUE TITLE
how to use it on termux

### ISSUE THREAD

**Issue by jcrnoob** [warifp/FacebookToolkit#4]
I have some problems with it...

**Comment by warifp** [comment]
you can use step in https://github.com/warifp/FacebookToolkit#Termux

**Comment by Basudev1** [comment]
My account is blocked by fb, so unable to create access token, any way to use it in Termux

**Comment by DINESH0419** [comment]
How to select the option on termux

**Comment by Jasonange** [comment]
> problèmes

Ça marche PHP run .php

**Comment by Arman7072** [comment]
I don't know how to use it on termux help please and I've installed it
