### ISSUE TITLE
How to use this tool

### ISSUE THREAD

**Issue by manaoton** [warifp/FacebookToolkit#50]
i don't know how to use this tools

![Screenshot_2021-05-16-13-12-13-101_com android systemui](https://user-images.githubusercontent.com/49203127/118389628-5aab2c00-b648-11eb-955e-f73001436d33.jpg)
# #

**Comment by Lord-Notrees** [comment]
That's because you're a retard. Just uninstall life.

**Comment by warifp** [comment]
Usage in here https://github.com/warifp/FacebookToolkit#usage
