### ISSUE TITLE
Unable to Facebook Toolkit `php run.php` in Kali Linux 2021.3

### ISSUE THREAD

**Issue by spragginsdesigns** [warifp/FacebookToolkit#57]
I have cloned the GitHub Repo to a directory I made in my home folder. 
Then I installed composer, and ran composer. 
I Ran `php run.php,` and nothing happened, including any other command. 
Did I miss something when I ran composer? 

Using:
VMware Workstation Pro 16.2 or 3
Kali Linux 2021.3
Tilix for Terminal Emulator, using non-sudo, and tried sudo as well.

**Comment by ALAHKONTOL** [comment]
same  ubuntu windows and xampp nothing happen

**Comment by spragginsdesigns** [comment]
> same

Let's start providing screenshots as well. 
Here is mine as root user, it does the same without being root though. 

![image](https://user-images.githubusercontent.com/43624199/144730324-646a64da-c56b-44c0-b5c1-d8f203ab69f1.png)

**Comment by gocyiv** [comment]
Did you solve this issue?

**Comment by spragginsdesigns** [comment]
> Did you solve this issue?

Nope, I even wiped my virtual machine of Kali Linux and reran it.

**Comment by haxjoker** [comment]
use apt install composer

**Comment by Isaulmoot** [comment]
> I have cloned the GitHub Repo to a directory I made in my home folder. Then I installed composer, and ran composer. I Ran `php run.php,` and nothing happened, including any other command. Did I miss something when I ran composer?
> 
> Using: VMware Workstation Pro 16.2 or 3 Kali Linux 2021.3 Tilix for Terminal Emulator, using non-sudo, and tried sudo as well.

(" HI, Frens! ")
chmod 777 run.php

**Comment by Isaulmoot** [comment]
> Did you solve this issue?

Im shocked no one figured this out. chmod 777 and chmod 775 are a double edged knife but here it's the solution. 

chmod 777 run.php 
It's a sudo file. Termux is never su.
