### ISSUE TITLE
$ git clone https://github.com/warifp/FacebookToolkit fatal: destination path 'FacebookToolkit' already exists and is not an empty directory. $

### ISSUE THREAD

**Issue by backhowless** [warifp/FacebookToolkit#6]
$ git clone https://github.com/warifp/FacebookToolkit
fatal: destination path 'FacebookToolkit' already exists and is not an empty directory.
$

Kenapa ya  ???
Atau saya ada yang salah

**Comment by warifp** [comment]
Itu folder sudah ada mas, coba tulis ' cd Facebook Toolkit ' terus tulis ' ls '

**Comment by backhowless** [comment]
Koq gini ya bang

Pada tanggal 26 Jun 2019 12.28 AM, "Wahyu Arif Purnomo" <
notifications@github.com> menulis:

Itu folder sudah ada mas, coba tulis ' cd Facebook Toolkit ' terus tulis '
ls '

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/warifp/FacebookToolkit/issues/6?email_source=notifications&email_token=AMMATLSZDMSWVK4YZEWPVK3P4JIT7A5CNFSM4H3KRLF2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODYQ7VYA#issuecomment-505543392>,
or mute the thread

**Comment by warifp** [comment]
Bisa kirim screenshotnya?

**Comment by ARJUNOPLOOP** [comment]
![Uploading Screenshot_2024-04-16-19-13-38-28_84d3000e3f4017145260f7618db1d683.jpg…]()
It's not working
