### ISSUE TITLE
can't enter token code

### ISSUE THREAD

**Issue by enesmertc** [warifp/FacebookToolkit#7]
hello does not react as shown below after running the application. 

https://hizliresim.com/M1yOjk

how do i solve this?

**Comment by warifp** [comment]
I can't see the image you sent, please send the screenshoot again

**Comment by enesmertc** [comment]
![M1yOjk](https://user-images.githubusercontent.com/52298362/60385265-1e8c7380-9a90-11e9-9414-be641d7b3674.png)

Here

**Comment by warifp** [comment]
I have activated it, please try again

**Comment by NTgitdude23** [comment]
Im having the same issue.
