### ISSUE TITLE
A option for send message all friends?

### ISSUE THREAD

**Issue by Cyb3rG0D7** [warifp/FacebookToolkit#8]
Existe una opción que permita enviar un mensaje específico a todos mis amigos ? o bien a una lista de perfiles incluidos en un .txt ya sea persona o fanpage, ademas de otra opción para postear en grupos algo específico, los grupos estarian en un .txt
gracias de antemano.

**Comment by warifp** [comment]
Tengo características como esa, pero es limitado hermano

**Comment by Cyb3rG0D7** [comment]
Quisiera unas opciones para spam
nosé si podrías añadir el código de estos proyectos a tu herramienta
https://github.com/barneyElDinosaurio/FbBot
https://github.com/nahimilega/Smart-Facebook-Spambot

**Comment by warifp** [comment]
Bien, gracias por ingresar y hacer referencia a amigos, buscaré una solución para agregar esta función, solo espera amigo, muchas gracias :)
